version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: attendance-mongodb-dev
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-attendance_system}
    volumes:
      - mongodb_data_dev:/data/db
      - ./docker/mongodb-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "27017:27017"
    networks:
      - attendance-network-dev
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend Server (Development)
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: server-development
    container_name: attendance-server-dev
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${SERVER_PORT:-5001}
      MONGODB_URI: ${MONGODB_URI:-mongodb://admin:password@mongodb:27017/attendance_system?authSource=admin}
      JWT_SECRET: ${JWT_SECRET:-dev-jwt-secret-key}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-7d}
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3001}
      CLIENT_PORT: ${CLIENT_PORT:-3001}
      SOCKET_CORS_ORIGIN: ${SOCKET_CORS_ORIGIN:-http://localhost:3001}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-10000}
      EMAIL_HOST: ${EMAIL_HOST:-smtp.gmail.com}
      EMAIL_PORT: ${EMAIL_PORT:-587}
      EMAIL_USER: ${EMAIL_USER:-}
      EMAIL_PASS: ${EMAIL_PASS:-}
      EMAIL_FROM: ${EMAIL_FROM:-noreply@attendance-system.com}
    volumes:
      - ./server:/app
      - /app/node_modules
      - server_uploads_dev:/app/uploads
    ports:
      - "5001:5001"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - attendance-network-dev
    command: ["npm", "run", "dev"]

  # Frontend Client (Development)
  client:
    build:
      context: .
      dockerfile: client/Dockerfile.dev
      target: client-development
    container_name: attendance-client-dev
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:5001/api}
      REACT_APP_SOCKET_URL: ${REACT_APP_SOCKET_URL:-http://localhost:5001}
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      server:
        condition: service_healthy
    networks:
      - attendance-network-dev
    command: ["npm", "start"]

volumes:
  mongodb_data_dev:
    driver: local
  server_uploads_dev:
    driver: local

networks:
  attendance-network-dev:
    driver: bridge 