import { PreferenceCategory, PreferenceField } from '../types';
import { Holiday } from '../types';

// Comprehensive list of timezones
export const TIMEZONES = [
  { value: 'UTC', label: 'UTC (Coordinated Universal Time)' },
  { value: 'America/New_York', label: 'Eastern Time (US & Canada)' },
  { value: 'America/Chicago', label: 'Central Time (US & Canada)' },
  { value: 'America/Denver', label: 'Mountain Time (US & Canada)' },
  { value: 'America/Los_Angeles', label: 'Pacific Time (US & Canada)' },
  { value: 'America/Anchorage', label: 'Alaska Time' },
  { value: 'Pacific/Honolulu', label: 'Hawaii Time' },
  { value: 'Europe/London', label: 'Greenwich Mean Time (London)' },
  { value: 'Europe/Paris', label: 'Central European Time (Paris)' },
  { value: 'Europe/Berlin', label: 'Central European Time (Berlin)' },
  { value: 'Europe/Rome', label: 'Central European Time (Rome)' },
  { value: 'Europe/Moscow', label: 'Moscow Time' },
  { value: 'Asia/Dubai', label: 'Gulf Standard Time (Dubai)' },
  { value: 'Asia/Kolkata', label: 'India Standard Time (Mumbai)' },
  { value: 'Asia/Shanghai', label: 'China Standard Time (Shanghai)' },
  { value: 'Asia/Tokyo', label: 'Japan Standard Time (Tokyo)' },
  { value: 'Asia/Seoul', label: 'Korea Standard Time (Seoul)' },
  { value: 'Australia/Sydney', label: 'Australian Eastern Time (Sydney)' },
  { value: 'Australia/Melbourne', label: 'Australian Eastern Time (Melbourne)' },
  { value: 'Australia/Perth', label: 'Australian Western Time (Perth)' },
];

// Languages
export const LANGUAGES = [
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Español (Spanish)' },
  { value: 'fr', label: 'Français (French)' },
  { value: 'de', label: 'Deutsch (German)' },
  { value: 'it', label: 'Italiano (Italian)' },
  { value: 'pt', label: 'Português (Portuguese)' },
  { value: 'ru', label: 'Русский (Russian)' },
  { value: 'zh', label: '中文 (Chinese)' },
  { value: 'ja', label: '日本語 (Japanese)' },
  { value: 'ko', label: '한국어 (Korean)' },
  { value: 'ar', label: 'العربية (Arabic)' },
  { value: 'hi', label: 'हिन्दी (Hindi)' },
];

// Currencies
export const CURRENCIES = [
  { value: 'USD', label: 'US Dollar ($)' },
  { value: 'EUR', label: 'Euro (€)' },
  { value: 'GBP', label: 'British Pound (£)' },
  { value: 'JPY', label: 'Japanese Yen (¥)' },
  { value: 'AUD', label: 'Australian Dollar (A$)' },
  { value: 'CAD', label: 'Canadian Dollar (C$)' },
  { value: 'CHF', label: 'Swiss Franc (CHF)' },
  { value: 'CNY', label: 'Chinese Yuan (¥)' },
  { value: 'INR', label: 'Indian Rupee (₹)' },
  { value: 'KRW', label: 'South Korean Won (₩)' },
];

// Notification sounds
export const NOTIFICATION_SOUNDS = [
  { value: 'default', label: 'Default' },
  { value: 'bell', label: 'Bell' },
  { value: 'chime', label: 'Chime' },
  { value: 'ding', label: 'Ding' },
  { value: 'tone', label: 'Tone' },
  { value: 'silent', label: 'Silent' },
];

// Quick actions for mobile
export const QUICK_ACTIONS = [
  { value: 'punch_in', label: 'Punch In' },
  { value: 'punch_out', label: 'Punch Out' },
  { value: 'request_leave', label: 'Request Leave' },
  { value: 'view_schedule', label: 'View Schedule' },
  { value: 'view_timesheet', label: 'View Timesheet' },
  { value: 'view_balance', label: 'View Leave Balance' },
];

// Preference Categories
export const PREFERENCE_CATEGORIES: PreferenceCategory[] = [
  {
    key: 'general',
    label: 'General',
    description: 'Basic system preferences and localization settings',
    icon: 'SettingsApplications',
  },
  {
    key: 'display',
    label: 'Display & Appearance',
    description: 'Customize the look and feel of your interface',
    icon: 'Palette',
  },
  {
    key: 'notifications',
    label: 'Notifications',
    description: 'Configure how and when you receive notifications',
    icon: 'Notifications',
  },
  {
    key: 'attendance',
    label: 'Attendance',
    description: 'Attendance tracking and reminder preferences',
    icon: 'Schedule',
  },
  {
    key: 'leave',
    label: 'Leave Management',
    description: 'Leave request and approval notification settings',
    icon: 'EventNote',
  },
  {
    key: 'reports',
    label: 'Reports & Analytics',
    description: 'Report generation and delivery preferences',
    icon: 'Analytics',
  },
  {
    key: 'privacy',
    label: 'Privacy & Security',
    description: 'Control your data sharing and privacy settings',
    icon: 'Shield',
  },
  {
    key: 'advanced',
    label: 'Advanced',
    description: 'Advanced system settings and beta features',
    icon: 'Security',
  },
  {
    key: 'mobile',
    label: 'Mobile',
    description: 'Mobile app specific preferences',
    icon: 'DeviceHub',
  },
  {
    key: 'integrations',
    label: 'Integrations',
    description: 'Third-party service integrations',
    icon: 'CloudSync',
  },
  {
    key: 'accessibility',
    label: 'Accessibility',
    description: 'Accessibility and usability options',
    icon: 'Accessibility',
  },
];

// Preference Fields
export const PREFERENCE_FIELDS: PreferenceField[] = [
  // General Settings
  {
    key: 'language',
    label: 'Language',
    description: 'Choose your preferred language for the interface',
    type: 'select',
    options: LANGUAGES,
    defaultValue: 'en',
    category: 'general',
  },
  {
    key: 'theme',
    label: 'Theme',
    description: 'Choose between light, dark, or system theme',
    type: 'select',
    options: [
      { value: 'light', label: 'Light' },
      { value: 'dark', label: 'Dark' },
      { value: 'auto', label: 'Auto (System)' },
    ],
    defaultValue: 'light',
    category: 'general',
  },
  {
    key: 'timezone',
    label: 'Timezone',
    description: 'Your local timezone for date and time display',
    type: 'select',
    options: TIMEZONES,
    defaultValue: 'UTC',
    category: 'general',
  },
  {
    key: 'dateFormat',
    label: 'Date Format',
    description: 'How dates should be displayed',
    type: 'select',
    options: [
      { value: 'MM/DD/YYYY', label: 'MM/DD/YYYY (US)' },
      { value: 'DD/MM/YYYY', label: 'DD/MM/YYYY (European)' },
      { value: 'YYYY-MM-DD', label: 'YYYY-MM-DD (ISO)' },
      { value: 'DD MMM YYYY', label: 'DD MMM YYYY (Text)' },
    ],
    defaultValue: 'MM/DD/YYYY',
    category: 'general',
  },
  {
    key: 'timeFormat',
    label: 'Time Format',
    description: 'How time should be displayed',
    type: 'select',
    options: [
      { value: '12', label: '12-hour (AM/PM)' },
      { value: '24', label: '24-hour' },
    ],
    defaultValue: '12',
    category: 'general',
  },
  {
    key: 'currency',
    label: 'Currency',
    description: 'Currency for financial displays',
    type: 'select',
    options: CURRENCIES,
    defaultValue: 'USD',
    category: 'general',
  },
  {
    key: 'numberFormat',
    label: 'Number Format',
    description: 'Number formatting style',
    type: 'select',
    options: [
      { value: 'US', label: '1,234.56 (US)' },
      { value: 'EU', label: '1.234,56 (European)' },
      { value: 'IN', label: '1,23,456.78 (Indian)' },
    ],
    defaultValue: 'US',
    category: 'general',
  },

  // Display Settings
  {
    key: 'dashboardLayout',
    label: 'Dashboard Layout',
    description: 'Choose your preferred dashboard layout',
    type: 'select',
    options: [
      { value: 'grid', label: 'Grid Layout' },
      { value: 'list', label: 'List Layout' },
      { value: 'compact', label: 'Compact Layout' },
    ],
    defaultValue: 'grid',
    category: 'display',
  },
  {
    key: 'sidebarCollapsed',
    label: 'Sidebar Auto-Collapse',
    description: 'Automatically collapse sidebar on smaller screens',
    type: 'switch',
    defaultValue: false,
    category: 'display',
  },
  {
    key: 'compactMode',
    label: 'Compact Mode',
    description: 'Use compact spacing and smaller elements',
    type: 'switch',
    defaultValue: false,
    category: 'display',
  },
  {
    key: 'showTooltips',
    label: 'Show Tooltips',
    description: 'Display helpful tooltips on hover',
    type: 'switch',
    defaultValue: true,
    category: 'display',
  },
  {
    key: 'animationsEnabled',
    label: 'Animations',
    description: 'Enable interface animations and transitions',
    type: 'switch',
    defaultValue: true,
    category: 'display',
  },
  {
    key: 'highContrast',
    label: 'High Contrast',
    description: 'Use high contrast colors for better visibility',
    type: 'switch',
    defaultValue: false,
    category: 'display',
  },
  {
    key: 'fontSize',
    label: 'Font Size',
    description: 'Adjust the base font size (12px - 20px)',
    type: 'slider',
    min: 12,
    max: 20,
    step: 1,
    defaultValue: 14,
    category: 'display',
  },

  // Notification Settings
  {
    key: 'emailNotifications',
    label: 'Email Notifications',
    description: 'Receive notifications via email',
    type: 'switch',
    defaultValue: true,
    category: 'notifications',
  },
  {
    key: 'smsNotifications',
    label: 'SMS Notifications',
    description: 'Receive notifications via SMS',
    type: 'switch',
    defaultValue: false,
    category: 'notifications',
  },
  {
    key: 'pushNotifications',
    label: 'Push Notifications',
    description: 'Receive browser/mobile push notifications',
    type: 'switch',
    defaultValue: true,
    category: 'notifications',
  },
  {
    key: 'browserNotifications',
    label: 'Browser Notifications',
    description: 'Show desktop notifications in browser',
    type: 'switch',
    defaultValue: true,
    category: 'notifications',
  },
  {
    key: 'soundEnabled',
    label: 'Notification Sounds',
    description: 'Play sounds for notifications',
    type: 'switch',
    defaultValue: true,
    category: 'notifications',
  },
  {
    key: 'notificationSound',
    label: 'Sound Type',
    description: 'Choose notification sound',
    type: 'select',
    options: NOTIFICATION_SOUNDS,
    defaultValue: 'default',
    category: 'notifications',
    dependsOn: { field: 'soundEnabled', value: true },
  },

  // Attendance Settings
  {
    key: 'attendanceReminders',
    label: 'Attendance Reminders',
    description: 'Get reminded to punch in/out',
    type: 'switch',
    defaultValue: true,
    category: 'attendance',
  },
  {
    key: 'reminderTime',
    label: 'Reminder Time',
    description: 'What time to send attendance reminders',
    type: 'time',
    defaultValue: '08:45',
    category: 'attendance',
    dependsOn: { field: 'attendanceReminders', value: true },
  },
  {
    key: 'autoBreakDeduction',
    label: 'Auto Break Deduction',
    description: 'Automatically deduct break time from total hours',
    type: 'switch',
    defaultValue: true,
    category: 'attendance',
  },
  {
    key: 'breakDuration',
    label: 'Break Duration',
    description: 'Default break duration in minutes',
    type: 'number',
    min: 15,
    max: 120,
    step: 15,
    defaultValue: 60,
    category: 'attendance',
    dependsOn: { field: 'autoBreakDeduction', value: true },
  },
  {
    key: 'overtimeNotifications',
    label: 'Overtime Notifications',
    description: 'Get notified when working overtime',
    type: 'switch',
    defaultValue: true,
    category: 'attendance',
  },
  {
    key: 'lateArrivalNotifications',
    label: 'Late Arrival Alerts',
    description: 'Get alerts for late arrivals',
    type: 'switch',
    defaultValue: true,
    category: 'attendance',
  },
  {
    key: 'earlyDepartureNotifications',
    label: 'Early Departure Alerts',
    description: 'Get alerts for early departures',
    type: 'switch',
    defaultValue: true,
    category: 'attendance',
  },
  {
    key: 'weekendReminders',
    label: 'Weekend Reminders',
    description: 'Send reminders on weekends if working',
    type: 'switch',
    defaultValue: false,
    category: 'attendance',
  },
  {
    key: 'holidayReminders',
    label: 'Holiday Reminders',
    description: 'Send reminders on holidays if working',
    type: 'switch',
    defaultValue: false,
    category: 'attendance',
  },

  // Leave Settings
  {
    key: 'leaveNotifications',
    label: 'Leave Notifications',
    description: 'Get notified about leave requests and updates',
    type: 'switch',
    defaultValue: true,
    category: 'leave',
  },
  {
    key: 'leaveApprovalNotifications',
    label: 'Approval Notifications',
    description: 'Get notified when leave is approved',
    type: 'switch',
    defaultValue: true,
    category: 'leave',
  },
  {
    key: 'leaveRejectionNotifications',
    label: 'Rejection Notifications',
    description: 'Get notified when leave is rejected',
    type: 'switch',
    defaultValue: true,
    category: 'leave',
  },
  {
    key: 'leaveBalanceReminders',
    label: 'Balance Reminders',
    description: 'Get reminders about low leave balance',
    type: 'switch',
    defaultValue: true,
    category: 'leave',
  },
  {
    key: 'lowBalanceThreshold',
    label: 'Low Balance Threshold',
    description: 'Number of days below which to send balance reminders',
    type: 'number',
    min: 1,
    max: 30,
    defaultValue: 5,
    category: 'leave',
    dependsOn: { field: 'leaveBalanceReminders', value: true },
  },
  {
    key: 'autoSubmitLeaveRequests',
    label: 'Auto-Submit Requests',
    description: 'Automatically submit leave requests after creation',
    type: 'switch',
    defaultValue: false,
    category: 'leave',
    advanced: true,
  },

  // Report Settings
  {
    key: 'weeklyReports',
    label: 'Weekly Reports',
    description: 'Receive weekly attendance summary reports',
    type: 'switch',
    defaultValue: false,
    category: 'reports',
  },
  {
    key: 'monthlyReports',
    label: 'Monthly Reports',
    description: 'Receive monthly attendance summary reports',
    type: 'switch',
    defaultValue: true,
    category: 'reports',
  },
  {
    key: 'reportFormat',
    label: 'Report Format',
    description: 'Preferred format for generated reports',
    type: 'select',
    options: [
      { value: 'pdf', label: 'PDF' },
      { value: 'excel', label: 'Excel (.xlsx)' },
      { value: 'csv', label: 'CSV' },
      { value: 'html', label: 'HTML' },
    ],
    defaultValue: 'pdf',
    category: 'reports',
  },
  {
    key: 'reportDelivery',
    label: 'Report Delivery',
    description: 'How reports should be delivered',
    type: 'select',
    options: [
      { value: 'email', label: 'Email' },
      { value: 'download', label: 'Download Link' },
      { value: 'both', label: 'Both' },
    ],
    defaultValue: 'email',
    category: 'reports',
  },
  {
    key: 'includeCharts',
    label: 'Include Charts',
    description: 'Include visual charts in reports',
    type: 'switch',
    defaultValue: true,
    category: 'reports',
  },
  {
    key: 'reportLanguage',
    label: 'Report Language',
    description: 'Language for generated reports',
    type: 'select',
    options: LANGUAGES,
    defaultValue: 'en',
    category: 'reports',
  },

  // Privacy Settings
  {
    key: 'profileVisibility',
    label: 'Profile Visibility',
    description: 'Who can see your profile information',
    type: 'select',
    options: [
      { value: 'public', label: 'Everyone' },
      { value: 'team', label: 'Team Members Only' },
      { value: 'managers', label: 'Managers Only' },
      { value: 'private', label: 'Private' },
    ],
    defaultValue: 'team',
    category: 'privacy',
  },
  {
    key: 'shareAttendanceData',
    label: 'Share Attendance Data',
    description: 'Allow sharing attendance data for analytics',
    type: 'switch',
    defaultValue: true,
    category: 'privacy',
  },
  {
    key: 'shareLeaveData',
    label: 'Share Leave Data',
    description: 'Allow sharing leave data for reporting',
    type: 'switch',
    defaultValue: true,
    category: 'privacy',
  },
  {
    key: 'allowManagerAccess',
    label: 'Manager Access',
    description: 'Allow managers to view detailed attendance data',
    type: 'switch',
    defaultValue: true,
    category: 'privacy',
  },
  {
    key: 'twoFactorReminders',
    label: '2FA Reminders',
    description: 'Get reminded to enable two-factor authentication',
    type: 'switch',
    defaultValue: true,
    category: 'privacy',
  },

  // Advanced Settings
  {
    key: 'enableBetaFeatures',
    label: 'Beta Features',
    description: 'Enable experimental beta features',
    type: 'switch',
    defaultValue: false,
    category: 'advanced',
    advanced: true,
  },
  {
    key: 'enableDebugMode',
    label: 'Debug Mode',
    description: 'Enable debug mode for troubleshooting',
    type: 'switch',
    defaultValue: false,
    category: 'advanced',
    advanced: true,
  },
  {
    key: 'dataRetentionPeriod',
    label: 'Data Retention',
    description: 'How long to keep your data (in months)',
    type: 'number',
    min: 12,
    max: 84,
    defaultValue: 24,
    category: 'advanced',
    advanced: true,
  },
  {
    key: 'autoLogout',
    label: 'Auto Logout',
    description: 'Automatically logout after inactivity',
    type: 'switch',
    defaultValue: true,
    category: 'advanced',
  },
  {
    key: 'autoLogoutTime',
    label: 'Auto Logout Time',
    description: 'Minutes of inactivity before auto logout',
    type: 'number',
    min: 5,
    max: 480,
    defaultValue: 30,
    category: 'advanced',
    dependsOn: { field: 'autoLogout', value: true },
  },
  {
    key: 'sessionTimeout',
    label: 'Session Timeout',
    description: 'Maximum session duration in hours',
    type: 'number',
    min: 1,
    max: 168,
    defaultValue: 24,
    category: 'advanced',
    advanced: true,
  },

  // Mobile Settings
  {
    key: 'locationTracking',
    label: 'Location Tracking',
    description: 'Allow location tracking for attendance',
    type: 'switch',
    defaultValue: true,
    category: 'mobile',
  },
  {
    key: 'backgroundSync',
    label: 'Background Sync',
    description: 'Sync data in the background',
    type: 'switch',
    defaultValue: true,
    category: 'mobile',
  },
  {
    key: 'offlineMode',
    label: 'Offline Mode',
    description: 'Enable offline functionality',
    type: 'switch',
    defaultValue: true,
    category: 'mobile',
  },
  {
    key: 'biometricLogin',
    label: 'Biometric Login',
    description: 'Use fingerprint/face unlock for login',
    type: 'switch',
    defaultValue: false,
    category: 'mobile',
  },
  {
    key: 'quickActions',
    label: 'Quick Actions',
    description: 'Available quick actions on mobile',
    type: 'multiselect',
    options: QUICK_ACTIONS,
    defaultValue: ['punch_in', 'punch_out', 'request_leave'],
    category: 'mobile',
  },

  // Integration Settings
  {
    key: 'calendarSync',
    label: 'Calendar Sync',
    description: 'Sync attendance with calendar',
    type: 'switch',
    defaultValue: false,
    category: 'integrations',
  },
  {
    key: 'calendarProvider',
    label: 'Calendar Provider',
    description: 'Choose your calendar provider',
    type: 'select',
    options: [
      { value: 'google', label: 'Google Calendar' },
      { value: 'outlook', label: 'Microsoft Outlook' },
      { value: 'apple', label: 'Apple Calendar' },
    ],
    defaultValue: 'google',
    category: 'integrations',
    dependsOn: { field: 'calendarSync', value: true },
  },
  {
    key: 'slackIntegration',
    label: 'Slack Integration',
    description: 'Enable Slack notifications and commands',
    type: 'switch',
    defaultValue: false,
    category: 'integrations',
  },
  {
    key: 'teamsIntegration',
    label: 'Microsoft Teams Integration',
    description: 'Enable Teams notifications and status updates',
    type: 'switch',
    defaultValue: false,
    category: 'integrations',
  },
  {
    key: 'webhookUrl',
    label: 'Webhook URL',
    description: 'Custom webhook URL for external integrations',
    type: 'text',
    defaultValue: '',
    category: 'integrations',
    advanced: true,
    validation: {
      pattern: '^(https?://.+)?$',
      message: 'Must be a valid HTTP/HTTPS URL',
    },
  },

  // Accessibility Settings
  {
    key: 'screenReader',
    label: 'Screen Reader Support',
    description: 'Enable screen reader optimizations',
    type: 'switch',
    defaultValue: false,
    category: 'accessibility',
  },
  {
    key: 'keyboardNavigation',
    label: 'Keyboard Navigation',
    description: 'Enhanced keyboard navigation support',
    type: 'switch',
    defaultValue: false,
    category: 'accessibility',
  },
  {
    key: 'reducedMotion',
    label: 'Reduced Motion',
    description: 'Reduce animations and motion effects',
    type: 'switch',
    defaultValue: false,
    category: 'accessibility',
  },
  {
    key: 'colorBlindMode',
    label: 'Color Blind Support',
    description: 'Color palette for color blind users',
    type: 'select',
    options: [
      { value: 'none', label: 'None' },
      { value: 'protanopia', label: 'Protanopia (Red-Green)' },
      { value: 'deuteranopia', label: 'Deuteranopia (Green-Red)' },
      { value: 'tritanopia', label: 'Tritanopia (Blue-Yellow)' },
    ],
    defaultValue: 'none',
    category: 'accessibility',
  },
  {
    key: 'largeText',
    label: 'Large Text',
    description: 'Use larger text for better readability',
    type: 'switch',
    defaultValue: false,
    category: 'accessibility',
  },
];

// Default preferences object
export const DEFAULT_PREFERENCES = PREFERENCE_FIELDS.reduce((acc, field) => {
  acc[field.key] = field.defaultValue;
  return acc;
}, {} as Record<string, any>);

// Official Holidays List (Sample)
export const OFFICIAL_HOLIDAYS: Holiday[] = [
  { date: '2024-01-01', name: 'New Year\'s Day', description: 'First day of the year' },
  { date: '2024-01-26', name: 'Republic Day', description: 'National holiday in India' },
  { date: '2024-03-29', name: 'Good Friday', description: 'Christian holiday' },
  { date: '2024-08-15', name: 'Independence Day', description: 'National holiday in India' },
  { date: '2024-10-02', name: 'Gandhi Jayanti', description: 'Birthday of Mahatma Gandhi' },
  { date: '2024-12-25', name: 'Christmas Day', description: 'Christian holiday' },
]; 